# Generated by Django 5.0.6 on 2024-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_load_top_scorers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Won'), (2, 'Lost')], default=0),
        ),
    ]
