# Generated by Django 5.0.6 on 2024-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_bet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Wrong'), (2, 'Good'), (3, 'Exact')], default=0),
        ),
    ]
