# Generated by Django 5.0.6 on 2024-06-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprediction',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
