# Generated by Django 5.0.6 on 2024-06-09 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_add_group_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
