# Generated by Django 5.0.6 on 2024-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_bet_created_at_bet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actual_away_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='actual_home_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
