# Generated by Django 5.0.6 on 2024-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_match_actual_away_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='final_score',
            field=models.BooleanField(default=False),
        ),
    ]
