# Generated by Django 5.0.6 on 2024-06-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_load_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score_submitted', models.BooleanField(default=False)),
                ('top_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_scorer', to='contest.topscorer')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='contest.team')),
            ],
        ),
    ]
